### ISSUE TITLE
大佬，可以加一个description吗

### ISSUE THREAD

**Issue by StrangeYear** [ShanaMaid/hexo-theme-shana#1]

**Comment by ShanaMaid** [comment]
@monian1916 你指的是使用教程吗？那部分有疑惑你直接提出来吧

**Comment by StrangeYear** [comment]
@ShanaMaid Markdown文档，头部可以自定义的那个description参数，在设定了这个参数之后，博客主页显示的是这个参数里面的内容，而不是<！--more-->前面的内容。

**Comment by ShanaMaid** [comment]
@monian1916 你说的这个问题该主题不提供解决方案，建议不设置description参数，自然就显示了
 前面的内容了。当然你也可以自己对该主题进行改造
