### ISSUE TITLE
遇到个问题，希望可以回答下啦，这主题太好看了

### ISSUE THREAD

**Issue by chenyinkai** [ShanaMaid/hexo-theme-shana#11]
这是我的博客，显示的是整篇文章内容，而不是像你那种有个  read more 按钮的，是还需要配置什么东西吗？目前我的配置文件就是复制你的。
你的：
![image](https://user-images.githubusercontent.com/22318156/29211461-d104dca6-7ecb-11e7-8f9c-215af9120ba1.png)

我的：
![image](https://user-images.githubusercontent.com/22318156/29211479-e03b79b4-7ecb-11e7-9fa4-88c0125c523d.png)

**Comment by ShanaMaid** [comment]
参照#5

**Comment by chenyinkai** [comment]
哇咔咔，太感谢了，主题也非常好看！！star一下，谢谢
