### ISSUE TITLE
shana 主题使用过程中的一些问题

### ISSUE THREAD

**Issue by zerocc2014** [ShanaMaid/hexo-theme-shana#12]
1. 主页 显示的是一篇篇完整的文章，不像你的主页那有还有 readMore
<img width="804" alt="71506341-b69b-415f-a112-7dfcbd4a7581" [](src="https://user-images.githubusercontent.com/16301538/29300566-b78628ae-81a8-11e7-8466-9d4cd90d4cb6.png">)

2. Markdown 语法貌似有点问题，代码块背景色咋调成纯黑色哇
<img width="826" alt="ca6ffaf8-209a-45c4-a098-5ab6c4910b84" src="https://user-images.githubusercontent.com/16301538/29300672-734122e2-81a9-11e7-8060-d6beefbfc4f0.png">
希望解答一哈谢谢😆

**Comment by ShanaMaid** [comment]
问题1: #5
问题2:  #4
