### ISSUE TITLE
shana 主题中的问题 

### ISSUE THREAD

**Issue by zerocc2017** [ShanaMaid/hexo-theme-shana#13]
昨天谢谢你回答啦
![c6961b44-4559-4950-bd4c-3488941efdeb](https://user-images.githubusercontent.com/30892505/29355723-af2f0a3e-82a4-11e7-9eb9-c3372d4edff6.png)
然而是这样的: (
<img width="699" alt="3ccc4f13d001e1adf9f3a7b6d2c0db30" src="https://user-images.githubusercontent.com/30892505/29355758-d6019adc-82a4-11e7-9c26-ad5b052df07f.png">

**Comment by ShanaMaid** [comment]
配置

修改hexo根目录下的 _config.yml

`language: zh-CN`

`theme: shana`

**Comment by zerocc2017** [comment]
😆 我的傻b了 没有上一篇文章所以左边没有。。。。代码高亮的问题 #4 只是代码去背景色，改成黑色了也不会高亮语法哇

**Comment by ShanaMaid** [comment]
语法高亮需要引入其余的插件，你去hexo官网上找找吧，当初没做语法高亮的适配

**Comment by zerocc2017** [comment]
搞不来 可以稍微指点下哇 改哪些地方 本人做移动端开发的

**Comment by zhaoqihui** [comment]
请问，read more 要怎么设置，为什么我的不显示read more 文章的全部内容是直接显示的，求指教

**Comment by ShanaMaid** [comment]
@zhaoqihui #5

**Comment by zhaoqihui** [comment]
非常感谢，解决了
