### ISSUE TITLE
怎么让一篇文章之显示一点然后点击查看全部

### ISSUE THREAD

**Issue by azhon** [ShanaMaid/hexo-theme-shana#15]
怎么让一篇文章之显示一点然后点击查看全部？

**Comment by aaaa9990aaaa** [comment]
我也想问……

**Comment by aaaa9990aaaa** [comment]
提问的老哥，我也遇到了这个问题。其实配置文件里面已经有配置项了
### excerpt_link: Read More
但因为大佬的文章有手动截取摘要或者用过其他工具，而很多人没有做这一步
所以在生成的时候post没有找到文章摘要
### 文件 article.ejs里面这句:<% if (post.excerpt&&index){ %>
###  因此即使配置了excerpt_link,依旧没办法展示摘要。
不废话，我这个菜鸡第一次看ejs，摸索了半天，找到两种解决方式，希望能帮到后面的小伙伴。
第一种：
这个比较简单，也比较推荐
 导入hexo-excerpt:  npm install hexo-excerpt --save
然后在hexo的 主配置文件(注意不是主题的配置文件)_config.yml里面添加如下配置：
### excerpt_depth: 2
这里表示默认截取标题和第一段文字，如果没有标题，就改成1。

第二种方法:
这里修改大佬ejs里面的代码，进行手动截取段落
文件:article.ejs 第28行，修改为：
```
<% var br = post.content.indexOf('\n') %>
  	<% if(br < 0 || !index) { %>
  	  <%- post.content %>
  	<% } else { %>
  	  <%- post.content.substring(0, br) %>
  	  <% if (theme.excerpt_link) { %>
        <p class="article-more-link">
          <a href="<%- config.root %><%- post.path %>#more"><%= theme.excerpt_link %></a>
        </p>
      <% } %>
  	<% } %>
```
这种方法也能默认截取第一段，但是如果第一段为代码段，可能会出bug，所以不是很推荐。
希望能帮到大家~
娜酱骑士团荣光永在！
顺便求个友链 http://reipanel.xyz 给我留言互粉哦~

**Comment by ShanaMaid** [comment]
@azhon @aaaa9990aaaa 你们看看这个 #5
