### ISSUE TITLE
可不可以再详细说明一下框架每个部分在md文件中的格式和存在的交互效果？

### ISSUE THREAD

**Issue by yyccQQu** [ShanaMaid/hexo-theme-shana#22]
新年快乐！
比如说，
![image](https://user-images.githubusercontent.com/32674176/36340757-1733ddc0-141e-11e8-8190-36c88dfcfd27.png)
这里面的
js，php两个标签是怎么放进内容里面的？

**Comment by ShanaMaid** [comment]
![image](https://user-images.githubusercontent.com/20333903/36340823-1cc2962c-141f-11e8-80fe-09425599e80a.png)

**Comment by yyccQQu** [comment]
恢复，这么快！3Q

**Comment by yyccQQu** [comment]
回复

**Comment by yyccQQu** [comment]
由于我是小白，所以希望大佬能多帮忙一下，谢谢。

![image](https://user-images.githubusercontent.com/32674176/36340895-da896d74-1420-11e8-86ee-ddc6a9d3784c.png)
这里面怎么再添加一个或多个标签

![image](https://user-images.githubusercontent.com/32674176/36340914-1fecba92-1421-11e8-9cf1-b5eee3e78686.png)
当我点击分类的时候跟我说的找不到文件，我该怎么办?

**Comment by ShanaMaid** [comment]
![image](https://user-images.githubusercontent.com/20333903/36340995-46369fc8-1422-11e8-99e5-5d12d835152f.png)
认真阅读使用说明，其余问题自行查阅hexo官网

**Comment by yyccQQu** [comment]
恩 谢谢 新年快乐
