### ISSUE TITLE
小姐姐有个手机兼容问题

### ISSUE THREAD

**Issue by xiaokar** [ShanaMaid/hexo-theme-shana#29]
1.手机上查看时会有左右可以拉的现象,点击文章才能恢复正常,
2.第一次点击更多文章时会出现直接跳到顶部的现象
小姐姐可以解决下吗

**Comment by ShanaMaid** [comment]
这周抽空看看，声明一下我不是小姐姐 щ(｀ω´щ) 。

**Comment by xiaokar** [comment]
真快速,3q威力末次

**Comment by 1373246212** [comment]
主题的便签什么的怎么做的，在那个文件夹

**Comment by ShanaMaid** [comment]
@1373246212 手写的，简单的css样式

**Comment by ShanaMaid** [comment]
@xiaokar 你根据自己的需求在body上设置
```
body {
   max-width: 1000px;
   margin: 0 auto;
}
```

1000px根据你的值修改

这个主题设计的初衷就没有考虑移动端的体验

**Comment by xiaokar** [comment]
设置后貌似没什么效果，能不能设置禁止缩放和禁止左右滑动，hexo搞不来
