### ISSUE TITLE
新手的一些问题

### ISSUE THREAD

**Issue by stdout-zhou** [ShanaMaid/hexo-theme-shana#31]
使用了您的主题搭了一个blog，但是我的blog上为什么不能折叠文本，也就是read more消失了。
另外请教一下如何修改代码区的颜色，希望能把红色改成透明色风格，就这样==。

**Comment by ShanaMaid** [comment]
read more：#5
代码高亮：https://github.com/ShanaMaid/hexo-theme-shana#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE

**Comment by stdout-zhou** [comment]
第一个问题成功解决了，第二个问题没描述清楚,,我想把代码区红色的改成白色或透明的在哪里修改呢（深色完全挡住了背景图），还有我的浏览器打开博客没有显示图标。
