### ISSUE TITLE
请问阅读次数的显示代码块在哪里

### ISSUE THREAD

**Issue by xiaokar** [ShanaMaid/hexo-theme-shana#34]
article.ejs找不到,其他的也都找了一遍
![_20181204112853](https://user-images.githubusercontent.com/40920747/49417204-ce7a5680-f7b7-11e8-9b33-91af64aa306b.png)

**Comment by ShanaMaid** [comment]
# leadcloud访问次数统计
# 
leancloud_visitors:
  enable: false
  app_id: 
  app_key:

**Comment by ghost** [comment]
请问文章的标题类型，在写文章的时候怎么定义

**Comment by xiaokar** [comment]
好的谢谢啦,也忘了之前要找对应代码的地方干嘛了,后来就直接配置了,谢谢楼主的主题,我的博客xiaok.fun和xiaok.xyz

**Comment by ghost** [comment]
@xiaokar 嗨，在写文章时候，文章归类的标签怎么弄

**Comment by xiaokar** [comment]
@CJ13067257052 我在外面,参考https://segmentfault.com/q/1010000009361385

**Comment by ghost** [comment]
@xiaokar 3Q
