### ISSUE TITLE
请问能否添加livere到代码中

### ISSUE THREAD

**Issue by troycizion123** [ShanaMaid/hexo-theme-shana#36]
请问能否添加livere到代码中？
或者简单的介绍下如何添加代码？
谢谢

**Comment by ShanaMaid** [comment]
@troycizion123 https://github.com/ShanaMaid/hexo-theme-shana#%E5%85%B3%E4%BA%8E%E4%B8%89%E6%96%B9%E8%AF%84%E8%AE%BA
