### ISSUE TITLE
还有个问题，谢大神了

### ISSUE THREAD

**Issue by JadenFK** [ShanaMaid/hexo-theme-shana#39]
我clone下来您的主题后，Read More不存在呀，想问下，您是怎么设置Read More的，我是小白，刚开始搞GitHub博客

**Comment by ShanaMaid** [comment]
md里加

**Comment by ShanaMaid** [comment]
```
<!-- more -->
```

**Comment by JadenFK** [comment]
谢谢啦，真挺好用。但是我的在主页面显示的长短是不是还要在.md里加个什么东西？就是我的文章在主页面是全部显示的，好长，然后下面有了一个read more

**Comment by JadenFK** [comment]
好像懂了，谢谢大神了
