### ISSUE TITLE
求分享shana主题的配置文件

### ISSUE THREAD

**Issue by zhangbiao11** [ShanaMaid/hexo-theme-shana#42]
你提供的主题相当好看，但是作为新手的我没法完整修改里边的配置文件，希望博主能够分享一下完全的文件！！！如果可以，那非常感谢，也不知道怎么联系，我留个邮箱吧，如果博主愿意给就发到2576998704@qq.com(或者就是我看不懂里边的配置信息)

**Comment by ShanaMaid** [comment]
readme有描述
