### ISSUE TITLE
关于更换背景出锅

### ISSUE THREAD

**Issue by oldherd** [ShanaMaid/hexo-theme-shana#43]
我更改了bg.css的链接以期望更改背景  
然而背景变成了“苟利……”等与长者有关的文字。  
请问应该怎么解决？

**Comment by ShanaMaid** [comment]
应该是你替换的链接不正确吧

**Comment by oldherd** [comment]
感谢大神，问题已经解决。在这里也说一下防止后面地人遇到：  
部分浏览器(比如chrome)加载失败(其实是浏览器对图床的请求超时)就会出现这样的问题。建议背景加入图床后若干时间再尝试。当然用360似乎不会出现这样的问题。

**Comment by ShanaMaid** [comment]
happy experience!
