### ISSUE TITLE
两个疑问求助大神

### ISSUE THREAD

**Issue by oldherd** [ShanaMaid/hexo-theme-shana#45]
1.如何修改文章显示区域的宽度(太窄的话代码一行放不下需要左右移动滑块阅读体验不是很高)
2.如何在首页置顶某一篇文章？
感谢

**Comment by skingorz** [comment]
置顶文章方法，随手搜到的，没有试过是否可行，建议遇到问题自己先搜一下在提问
https://blog.csdn.net/qwerty200696/article/details/79010629

**Comment by oldherd** [comment]
抱歉，上古时期的制杖问题，打扰了
