### ISSUE TITLE
文章

### ISSUE THREAD

**Issue by geekzw** [ShanaMaid/hexo-theme-shana#5]
请问我的文章是显示全部的，主页列表只显示摘要是哪个属性控制的

**Comment by ShanaMaid** [comment]
![image](https://user-images.githubusercontent.com/20333903/28317150-5e8b36d8-6bf8-11e7-84e5-9158c8d7b5a5.png)

**Comment by chenyinkai** [comment]
哇咔咔，太感谢了，主题也非常好看！ star一下。谢谢

**Comment by bkfish** [comment]
还要配置其他的吗 单纯好像不行

**Comment by bkfish** [comment]
已解决 打扰了
