### ISSUE TITLE
markdown解析问题

### ISSUE THREAD

**Issue by li-lgw** [ShanaMaid/hexo-theme-shana#6]
> 引用>不生效

**Comment by ShanaMaid** [comment]
引用是能生效的，大概你姿势错了？
如下图:
![image](https://user-images.githubusercontent.com/20333903/28357497-31728ac4-6c9e-11e7-8ade-d33a7a93795e.png)
![image](https://user-images.githubusercontent.com/20333903/28357503-35e760fc-6c9e-11e7-8c36-881c5798a35c.png)
