### ISSUE TITLE
关于维护

### ISSUE THREAD

**Issue by li-lgw** [ShanaMaid/hexo-theme-shana#7]
请问题主还会维护么？比如网易云跟帖月底停止服务了，有考虑加相册功能么？

**Comment by ShanaMaid** [comment]
月底应该会抽时间把评论换成搜狐的畅言，至于相册功能你可以自己新开一个页面插入图片。

**Comment by ShanaMaid** [comment]
@li-lgw 评论已替换为友言，详情请阅读README.md

**Comment by li-lgw** [comment]
@ShanaMaid 感谢你，我是小白，还在努力成长中
